import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { NavbarMenu } from "@/components/NavbarMenu";
import { MaterialTailwindControllerProvider } from "@/context";
import { ThemeProvider } from "../app/MTailwind";
import Configurator from "@/components/Configurator";
import Footer from "@/components/Footer";
import { Sidenav } from "@/components/Sidenav";
import ButtonConfigurator from "@/components/ButtonConfigurator";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <ThemeProvider>
          <MaterialTailwindControllerProvider>
            <div className="min-h-screen bg-blue-gray-50/50">
              <Sidenav />
              <div className="p-4 xl:ml-80">
                <NavbarMenu />
                {children}
                <Configurator />
                <ButtonConfigurator />
                <div className="text-blue-gray-600 relative">
                  <Footer />
                </div>
              </div>
            </div>
          </MaterialTailwindControllerProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
