import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { MaterialTailwindControllerProvider } from "@/context";
import { ThemeProvider } from "../app/MTailwind";
import PageLayout from "@/components/Layouts/PageLayout";
import { Providers } from "./providers";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Point of Sales",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <ThemeProvider>
          <Providers>
            <MaterialTailwindControllerProvider>
              <div className="min-h-screen bg-blue-gray-50/50">
                <PageLayout>{children}</PageLayout>
              </div>
            </MaterialTailwindControllerProvider>
          </Providers>
        </ThemeProvider>
      </body>
    </html>
  );
}
